### PR TITLE
Fix react warnings

### PR DESCRIPTION
**Pull request by prabhavnegi**
Made changes in the code no warnings now.

### CODE REVIEW

**Comment by djhemath** [comment]
First of all, thanks for the contribution. It means a lot to me. People like you are making the open source community a great place! Kudos!

However, I see some issues with the PR.
1. In the `HelpButton` component, I see that you're using **index** as key. It's not generally advisable, I left a [comment](https://github.com/djhemath/snap-nostr/pull/9#discussion_r1884218269) in this PR for you. Please check that out.
2. I can see that you fixed the property names of SVGs like `stroke-width`, `stroke-linecap`, etc. Nice, but it's done only for certain icons. There are still some icons with `stroke-linecap`, `stroke-linejoin`, etc. It'll be really helpful if you can fix that as well.


If you need any more clarifications or any suggestions, feel free to leave a message. I'm more than happy to spend my time with people like you!

**Comment by prabhavnegi** [comment]
Hi @djhemath
I have made the changes regarding the key for helpbutton.
For SVG icons, I couldn't find to icons to make the changes.

**Comment by djhemath** [comment]
Yep, there are no icons left to make the change. I made a lil mistake when reviewing that part. Sorry for the confusion.
All looks good to me, merging it.

Thanks for your contribution!

**Comment by prabhavnegi** [comment]
@djhemat 💪😄

**Pull request merged**
